### ISSUE TITLE
ComplexBeanProbe Bug

### ISSUE THREAD

**Issue by lazyp** [mybatis/ibatis-2#1]
In The getPropertyTypeForGetter Method , as follow code
type = ClassInfo.getInstance(type).getSetterType(name);
not Get actual type of Generic ,but direct return Object Type.
lead to a exception " com.ibatis.common.beans.ProbeException: There is no READABLE property named 'xxx' in class 'java.lang.Object' "

**Comment by hazendaz** [comment]
Closing issue as very old and this library set is unsupported at this point.  If a pull request for same comes along it will be merged and release made.  Issue alone will not get anything fixed unfortunately.
