### ISSUE TITLE
BasicResultMap Bug

### ISSUE THREAD

**Issue by chfly2000** [mybatis/ibatis-2#5]
In BasicResultMap, the ResultMapping will be set to a ThreadLocal variable named remappableResultMappings when allowRemapping is true, but the DataExchange not. There is an ArrayIndexOutOfBoundsException when multi-thread call the statement with dynamic select part.

**Comment by hazendaz** [comment]
Closing issue as very old and this library set is unsupported at this point.  If a pull request for same comes along it will be merged and release made.  Issue alone will not get anything fixed unfortunately.
