### ISSUE TITLE
Lost version (ibatis-common-2 2.0.9B)

### ISSUE THREAD

**Issue by felipecaparelli** [mybatis/ibatis-2#51]
I'm looking for the ibatis-common-2 jar version from 2005/02/20 but it is not available in any maven repository. Can you provide it to me directly?

**Comment by kazuki43zoo** [comment]
I don't know about ibatis-common-2.

@mybatis/committers Who is know it?

**Comment by christianpoitras** [comment]
I remember seeing this many years ago. It seems to exists in the first commit of iBatis since there is a folder called `src/main/java/com/ibatis/common/`.
Recovering such a jar may be difficult or impossible. I will check with in the repos of projects I was working on around 2005.

**Comment by christianpoitras** [comment]
I was able to recover ibatis-common-2, ibatis-dao-2 and ibatis-sqlmap-2 jars version 2.1.7 from 2006 from a very old repo. I cannot guaranty that they are were not altered, but they worked as far as I can remember.

**Comment by christianpoitras** [comment]
The originals are on Maven Central, so it's not very useful. I will not be able to recover the version 2.0.9B.

**Comment by harawata** [comment]
This archive contains a jar named ibatis-common-2.jar
https://osdn.net/projects/sfnet_ibatisdb/downloads/ibatisdb-2/2.0.9b/iBATIS_DBL-2.0.9b.550.zip/
There are a few other archives.
https://osdn.net/projects/sfnet_ibatisdb/

**Comment by felipecaparelli** [comment]
Thank you so much. I'll try this jar and if everything works fine I'll tell to you. This is what I call Artifactology ;)

**Comment by hazendaz** [comment]
Closing issue as this was more of a question than issue on legacy code.
