### ISSUE TITLE
useSetObjectForNullValue not set to TRUE for MSSQL JDBC driver

### ISSUE THREAD

**Issue by rumessh** [mybatis/ibatis-2#66]
jdbcDriverName doesn't start with Microsoft SQL Server. https://github.com/microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java#L445

https://github.com/microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java#L982

Created a PR to address this issue -> https://github.com/mybatis/ibatis-2/pull/65

**Comment by hazendaz** [comment]
PR #65 merged fixing issue.
